name: Nightly

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  micro_ros_idf:
    strategy:
      fail-fast: false
      matrix:
        branch: [humble, jazzy, kilted, rolling]
    uses: ./.github/workflows/ci.yml
    with:
      branch: ${{ matrix.branch }}
